### ISSUE TITLE
Error build in React.js

### ISSUE THREAD

**Issue by pasalino** [stecb/qsomeness#2]
When i tried to build react package, create-react-app return this:

![image](https://user-images.githubusercontent.com/18738567/44776621-cb4c4a80-ab78-11e8-9c21-cccc3c118521.png)

And this is link for details:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

I think we need a babel to transpile. Right?

**Comment by ksnll** [comment]
We either
- Remove es6 functionalities from our code (arrows & spread operators)
- Build and ship also a transpiled version

@stecb do you have any opinions on this?

**Comment by stecb** [comment]
@ksnll @pasalino sorry for the delay. I had in mind to add the transpiled version (ie under a `dist` folder), so the 2nd option would be ideal IMHO.

**Comment by stecb** [comment]
Solved by https://github.com/stecb/qsomeness/pull/3
